apiVersion: apps/v1
kind: Deployment
metadata:
  name: proper-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proper-solution
  template:
    metadata:
      labels:
        app: proper-solution
    spec:
      containers:
      - name: proper-solution
        image: yougurti/proper-solution:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: proper-solution-service
spec:
  selector:
    app: proper-solution
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proper-solution-ingress
spec:
  rules:
  - host: proper-solution.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proper-solution-service
            port:
              number: 80